application: adamcodez
version: 1
runtime: java

handlers:
       
 - url: /*
   name: OAuthFilter
   filter: com.adamvduke.dowhatnow.services.OAuthFilter
   secure: always

 - url: /alerts/schedule.json
   name: ScheduleAlert
   servlet: com.adamvduke.dowhatnow.services.alert.ScheduleAlert
   secure: always
   
 - url: /alerts/show.json
   name: ShowAlerts
   servlet: com.adamvduke.dowhatnow.services.alert.ShowAlerts
   secure: always
   
welcome_files:
 - index.html

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties

ssl_enabled: true