application: adamcodez
version: 1
runtime: java

# enable warmup requests
inbound_services:
 - warmup

handlers:
    
 - url: /*
   name: GuiceFilter
   filter: com.google.inject.servlet.GuiceFilter
   secure: always
   
listeners:
 - com.adamvduke.dowhatnow.config.guice.DoWhatNowGuiceConfig

welcome_files:
 - index.html

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties
  appengine.maximum-request-length: 500
  appengine.all-invocation-interceptor.active: false
  
ssl_enabled: true